### PR TITLE
Add first line of text.

### LINKED ISSUE #141: Changelog test with multiple contributors
Test how the changelog looks like for a feature with multiple contributors.

### PR DESCRIPTION
**Pull request by mikenikles**
## Description 
A test for a changelog entry with multiple contributors.

## Related Issue(s)
Fixes #141 

## How to test
1. Make sure at least 2 people contributed to the `multiple-contributors.txt` file
2. Merge the PR
3. Ensure all contributors are mentioned in the `CHANGELOG.md` file

## Release Notes

```release-note
docs(misc): Add a bit of text.
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod-test-repo/pull/142#" title="Author self-approved">mikenikles</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **arthursens** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @arthursens` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=gitpod-io%2Fgitpod-test-repo).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod-test-repo/blob/1test/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by mikenikles** [comment]
@JanKoehnlein could you please commit a line of text to the file in this PR?

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitpod-test-repo/pull/142#issuecomment-911927128" title="Approved">mikenikles</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **arthursens** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @arthursens` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=gitpod-io%2Fgitpod-test-repo).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitpod-test-repo/blob/1test/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
