### PR TITLE
I wanna play with prow too!

### PR DESCRIPTION
**Pull request by ArthurSens**
Signed-off-by: ArthurSens <arthursens2005@gmail.com>

### CODE REVIEW

**Comment by ArthurSens** [comment]
this is a super important PR

/cc @meysholdt

**Comment by ArthurSens** [comment]
this is freaking awesome :shipit:

**Comment by ArthurSens** [comment]
alright, enough playing around
/close

**Comment by leodido** [comment]
No [goose](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/goose) plugin? I'm sad now.

**Comment by csweichel** [comment]
No goose plug-in **yet** :)

**Pull request closed without merging**
